FROM arm32v7/ruby:latest
COPY qemu-arm-static /usr/bin
LABEL maintainer="dragonchaser <maptool@datenschmutz.space>"
EXPOSE 4567
RUN git clone http://github.com/dragonchaser/maptool /maptool
WORKDIR /maptool
RUN bundle install
CMD ["ruby", "app.rb"]
